version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "*"
        dependency-type: "production"
    assignees:
      - "tomahawk_pilot"
    labels:
      - "yarn"
      - "dependencies"
