# Number of days of inactivity before an issue becomes stale
daysUntilStale: 7
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - good to merge
  - waiting for back end
  - waiting for related PR
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Hi,
  This pr/issue has been automatically marked as stale because it has not had any recent activity.
  It will be closed if no further activity occurs for 7 more days. Thank you for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Hi, @gigincg, @nihal467, @khavinshankar, @mathew-alex 
  This pr/issue has been automatically closed because it has not had any recent activity.
  Thank you for your contributions. Feel free to repopen the pr/issue.
# Issue specific properties
issue:
  # Inactivity time for issue to be considered stale
  daysUntilStale: 14
  # No auto closing the issues
  daysUntilClose: false
  # Comment to post when marking an issue as stale.
  markComment: >
    Hi, @gigincg, @nihal467, @khavinshankar, @mathew-alex 
    This issue has been automatically marked as stale because it has not had any recent activity.

