[build]
publish = "build/"
environment = { NPM_FLAGS = "--legacy-peer-deps" }

[[redirects]]
from = "/api/*"
to = "https://careapi.coronasafe.in/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
