name: Cypress Tests

on:
  schedule:
    - cron: "30 22 * * *"
  pull_request:
    branches:
      - develop
      - master
  workflow_dispatch:

jobs:
  cypress-run:
    permissions: write-all
    if: github.repository == 'coronasafe/care_fe'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v3

      - name: Checkout care 📥
        uses: actions/checkout@v3
        with:
          repository: coronasafe/care
          path: care

      - name: Start care docker containers 🐳
        run: |
          cd care
          make docker_config_file=docker-compose.pre-built.yaml up 
          while docker compose exec backend bash -c "python manage.py showmigrations 2>/dev/null | cat | grep -q '\[ \]'"; do
            >&2 echo "Migrations are not yet applied - sleeping"
            sleep 5
          done
          echo "Migrations are applied"
          cd ..

      - name: Load dummy data into care backend 📂
        run: |
          cd care
          docker compose exec backend bash -c "python manage.py load_dummy_data"
          cd ..

      - name: Check care is up ♻
        run: curl -o /dev/null -s -w "%{http_code}\n" http://localhost:9000

      - name: Install dependencies 📦
        run: npm install

      - name: Build & Compile rescript files ⚙️
        run: "npm run build"

      - name: Cypress run 🥬
        uses: cypress-io/github-action@v5
        with:
          env: SKIP_PREFLIGHT_CHECK=true
          install: false
          start: "npx vite preview --host"
          wait-on: "http://localhost:4000"
          wait-on-timeout: 300
          browser: chrome
          record: true
        env:
          CARE_API: http://localhost:9000
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Remove cypress passed label on failure 🏷️
        uses: actions-ecosystem/action-remove-labels@v1
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: cypress passed

      - name: Add cypress passed label on success 🏷️
        uses: actions-ecosystem/action-add-labels@v1
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: cypress passed

      - name: Remove cypress failed label on success 🏷️
        uses: actions-ecosystem/action-remove-labels@v1
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: cypress failed

      - name: Add cypress failed label on failure 🏷️
        uses: actions-ecosystem/action-add-labels@v1
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: cypress failed

      - name: Upload cypress screenshots on failure 📸
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

