name: Cypress Tests

on:
  pull_request:
    branches:
      - develop
      - master
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: yarn start
          wait-on: 'http://localhost:4000'
          wait-on-timeout: 300
          browser: electron
      - name: Upload cypress test error screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
            # Test run video was always captured, so this action uses "always()" condition
      - name: Upload cypress test videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
