name: Sync with upstream
on: 
  schedule:
    - cron: '* 00 * * *'
  workflow_dispatch:
    inputs:
      branch:
          description: 'Enter branch name to sync from upstream'
          required: true
          default: 'develop'

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync Repo
        run: gh repo sync ${{ github.repository }} -b ${{ inputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
