name: Sync with upstream
on: 
  schedule:
    - cron: '* 00 * * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: coronasafe/care_fe    # set the upstream repo
          upstream-branch: develop   # set the upstream branch to merge from
          branch: develop          # set the branch to merge to
          token: ${{ secrets.GITHUB_TOKEN }}  # set the token to push to the repo
