name: Sync with upstream
on: 
  schedule:
    - cron: '* 00 * * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync Repo
        run: gh repo sync ${{ github.repository }} -b develop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
